Repository nicolas2321-ux/proyectoncapas, pull requests merged in 2023-11, with the labels that each got.

#3 :wrench:Actualizando paginacion Controller
  API/api/src/main/java/com/example/demo/controllers/EventoController.java
  API/api/src/main/java/com/example/demo/controllers/PublicController.java
  API/api/src/main/java/com/example/demo/controllers/dto/PageDTO.java
  API/api/src/main/java/com/example/demo/implementation/EventoImpl.java
  API/api/src/main/java/com/example/demo/services/EventoService.java
  API/api/src/main/java/com/example/demo/utils/WebSecurityConfiguration.java
  API/api/src/main/resources/application.properties
Labels: Revision

#6 :bug:Solucion de error de Rol por defecto
  Server/api/src/main/java/com/example/demo/controllers/UserController.java
  Server/api/src/main/java/com/example/demo/model/entities/User_rol.java
  Server/api/src/main/java/com/example/demo/repository/RolRepository.java
  Server/api/src/main/java/com/example/demo/repository/UserRepository.java
  Server/api/src/main/java/com/example/demo/services/implementation/user_RolImpl.java
  Server/api/src/main/java/com/example/demo/services/user_rolService.java
Labels: bug

#7 Feature login
  Server/api/src/main/java/com/example/demo/controllers/UserController.java
  Server/api/src/main/java/com/example/demo/model/entities/User_rol.java
  Server/api/src/main/java/com/example/demo/repository/RolRepository.java
  Server/api/src/main/java/com/example/demo/repository/UserRepository.java
  Server/api/src/main/java/com/example/demo/services/implementation/user_RolImpl.java
  Server/api/src/main/java/com/example/demo/services/user_rolService.java
Labels: Revision

#8 :sparkles:Agregando el Navbar y Footer
  Client/smug-tickets/package-lock.json
  Client/smug-tickets/package.json
  Client/smug-tickets/postcss.config.js
  Client/smug-tickets/src/App.jsx
  Client/smug-tickets/src/assets/Presentacion1.png
  Client/smug-tickets/src/assets/Presentacion2.png
  Client/smug-tickets/src/assets/Presentacion3.png
  Client/smug-tickets/src/assets/smug_ticket.png
  Client/smug-tickets/src/components/Carousel/Carousel.jsx
  Client/smug-tickets/src/components/Footer/Footer.jsx
  Client/smug-tickets/src/components/Navbar/NavbarHomepage.jsx
  Client/smug-tickets/src/pages/user/Home.jsx
  Client/smug-tickets/tailwind.config.js
Labels: Revision

#9 :lipstick:Agregando Estilo de la Card y Servicio de Eventos + Paginación
  Client/smug-tickets/.env
  Client/smug-tickets/package-lock.json
  Client/smug-tickets/package.json
  Client/smug-tickets/src/components/Card/CardHome.jsx
  Client/smug-tickets/src/pages/user/Home.jsx
  Client/smug-tickets/src/services/Publico/PublicService.js
Labels: Revision

#10 :lock:Agregando AuthContext para almacenar el token del usuario
  Client/smug-tickets/package-lock.json
  Client/smug-tickets/package.json
  Client/smug-tickets/src/Context/UserContext.js
  Client/smug-tickets/src/auth/AuthContext.js
  Client/smug-tickets/src/auth/AuthReducer.js
  Client/smug-tickets/src/services/Auth/AuthService.js
  Client/smug-tickets/src/services/Auth/RolService.js
  Client/smug-tickets/src/services/Publico/PublicService.js
Labels: Revision

#22 Componente de Registro
  Client/smug-tickets/package-lock.json
  Client/smug-tickets/package.json
  Client/smug-tickets/src/App.jsx
  Client/smug-tickets/src/pages/user/AuthGoogle.jsx
  Client/smug-tickets/src/pages/user/GoogleRegister.jsx
  Client/smug-tickets/tailwind.config.js
Labels: Revision

#28 :heavy_plus_sign: Añadir React Router
  Client/smug-tickets/package-lock.json
  Client/smug-tickets/package.json
  Client/smug-tickets/src/App.jsx
  Client/smug-tickets/src/components/Navbar/NavbarHomepage.jsx
  Client/smug-tickets/src/pages/user/GoogleRegister.jsx
  Client/smug-tickets/src/pages/user/Home.jsx
  Client/smug-tickets/src/routes/AppRouter.jsx
  Client/smug-tickets/yarn.lock
  Server/api/src/main/java/com/example/demo/utils/CorsConfig.java
Labels: enhancement

#30 :lipstick: Agregando pages de Admin
  Client/smug-tickets/src/pages/admin/CreatEvent.jsx
  Client/smug-tickets/src/pages/admin/EditEvent.jsx
  Client/smug-tickets/src/pages/admin/FinishedEvents.jsx
  Client/smug-tickets/src/pages/admin/GraphEvent.jsx
  Client/smug-tickets/src/pages/admin/GraphEvents.jsx
  Client/smug-tickets/src/pages/admin/ListOfLocations.jsx
  Client/smug-tickets/src/pages/admin/NewLocation.jsx
  Client/smug-tickets/src/pages/admin/UpcomingEvents.jsx
  Client/smug-tickets/src/pages/admin/UserManagement.jsx
  Client/smug-tickets/src/types/types.js
  Client/smug-tickets/yarn.lock
Labels: help wanted

#34 :bug:Solución de error en la petición de registro de la api
  Client/smug-tickets/.gitignore
  Server/api/src/main/java/com/example/demo/model/dto/UserRegistrationDto.java
Labels: bug

#35 :bug:Solución a error de paginación
  Client/smug-tickets/src/pages/user/Home.jsx
  Client/smug-tickets/yarn.lock
Labels: bug

#37 :sparkles: El login funciona
  Client/smug-tickets/src/pages/user/AuthGoogle.jsx
Labels: enhancement

#39 :bug:Solución del error sobre los roles de un usuario
  Client/smug-tickets/src/pages/user/AuthGoogle.jsx
  Client/smug-tickets/src/services/Auth/RolService.js
Labels: bug

#45 :sparkles:Funcionalidad de crear evento
  Client/smug-tickets/src/pages/admin/CreatEvent.jsx
  Client/smug-tickets/src/routes/AppRouter.jsx
  Client/smug-tickets/src/services/Category/CategoryService.js
  Client/smug-tickets/src/services/Event/EventService.js
Labels: Revision

#52 :sparkles:Funcionalidad de Editar un evento
  Client/smug-tickets/src/pages/admin/EditEvent.jsx
  Client/smug-tickets/src/routes/AppRouter.jsx
  Client/smug-tickets/src/services/Event/EventService.js
Labels: Revision

#56 :art:Estructurando el service de user
  Client/smug-tickets/src/pages/admin/UserManagement.jsx
  Client/smug-tickets/src/services/Users/UsersService.js
Labels: Revision

#63 :sparkles:Navbar Admin funcional
  Client/smug-tickets/src/components/Card/CardModify.jsx
  Client/smug-tickets/src/components/Navbar/NavbarAdmin.jsx
  Client/smug-tickets/src/pages/admin/CreatEvent.jsx
  Client/smug-tickets/src/pages/admin/EditEvent.jsx
  Client/smug-tickets/src/pages/admin/FinishedEvents.jsx
  Client/smug-tickets/src/pages/admin/GraphEvent.jsx
  Client/smug-tickets/src/pages/admin/GraphEvents.jsx
  Client/smug-tickets/src/pages/admin/HomeAdmin.jsx
  Client/smug-tickets/src/pages/admin/ListOfLocations.jsx
  Client/smug-tickets/src/pages/admin/NewLocation.jsx
  Client/smug-tickets/src/pages/admin/UpcomingEvents.jsx
  Client/smug-tickets/src/pages/admin/UserManagement.jsx
  Client/smug-tickets/src/pages/user/AuthGoogle.jsx
  Client/smug-tickets/src/routes/AppRouter.jsx
Labels: Revision

#70 :sparkles:Navbar Cliente funcional
  Client/smug-tickets/src/components/Card/CardHome.jsx
  Client/smug-tickets/src/components/Card/CardMyTicket.jsx
  Client/smug-tickets/src/components/Navbar/NavbarUser.jsx
  Client/smug-tickets/src/pages/user/AuthGoogle.jsx
  Client/smug-tickets/src/pages/user/Home.jsx
  Client/smug-tickets/src/pages/user/MyTIckets.jsx
  Client/smug-tickets/src/pages/user/Record.jsx
  Client/smug-tickets/src/pages/user/ViewEvent.jsx
  Client/smug-tickets/src/routes/AppRouter.jsx
Labels: Revision

#80 :white_check_mark:Actualizando petición getLocalidades
  Client/smug-tickets/src/components/Navbar/NavbarAdmin.jsx
  Client/smug-tickets/src/routes/AppRouter.jsx
Labels: Revision

#81 Feature search
  Client/smug-tickets/package-lock.json
  Client/smug-tickets/package.json
  Client/smug-tickets/src/components/Navbar/NavbarUser.jsx
  Client/smug-tickets/src/components/SearchBox/SearchBox.jsx
  Client/smug-tickets/src/pages/admin/CreatEvent.jsx
  Client/smug-tickets/src/pages/admin/GraphEvents.jsx
  Client/smug-tickets/src/pages/admin/HomeAdmin.jsx
  Client/smug-tickets/src/pages/admin/UpcomingEvents.jsx
  Client/smug-tickets/src/pages/user/Home.jsx
  Client/smug-tickets/src/pages/user/MyTIckets.jsx
  Client/smug-tickets/src/services/Event/EventService.js
  Server/api/src/main/java/com/example/demo/utils/WebSecurityConfiguration.java
Labels: Revision

#83 :sparkles: Historial hecho
  Client/smug-tickets/src/components/Card/CardHome.jsx
  Client/smug-tickets/src/components/Card/CardRecord.jsx
  Client/smug-tickets/src/pages/user/Record.jsx
  Client/smug-tickets/src/services/Ticket/TicketService.js
Labels: help wanted

#89 :sparkles:Agregando funcionalidad mis Tickets
  Client/smug-tickets/package-lock.json
  Client/smug-tickets/src/components/Card/CardMyTicket.jsx
  Client/smug-tickets/src/pages/user/MyTIckets.jsx
  Client/smug-tickets/src/pages/user/TransferTicket.jsx
  Client/smug-tickets/src/routes/AppRouter.jsx
Labels: Revision

#96 :sparkles:LectorQR funcional
  Client/smug-tickets/src/components/Navbar/NavbarQR.jsx
  Client/smug-tickets/src/pages/admin/LectorQR.jsx
  Client/smug-tickets/src/pages/user/AuthGoogle.jsx
  Client/smug-tickets/src/routes/AppRouter.jsx
  Client/smug-tickets/src/routes/DashboardClient.jsx
  Client/smug-tickets/src/routes/Private.jsx
  Client/smug-tickets/src/services/Ticket/TicketService.js
Labels: Revision

#99 :iphone:Implementación de PWA
  Client/smug-tickets/index.html
  Client/smug-tickets/package-lock.json
  Client/smug-tickets/package.json
  Client/smug-tickets/public/android-chrome-192x192.png
  Client/smug-tickets/public/apple-touch-icon.png
  Client/smug-tickets/public/browserconfig.xml
  Client/smug-tickets/public/favicon-16x16.png
  Client/smug-tickets/public/favicon-32x32.png
  Client/smug-tickets/public/favicon.ico
  Client/smug-tickets/public/mstile-150x150.png
  Client/smug-tickets/public/safari-pinned-tab.svg
  Client/smug-tickets/public/site.webmanifest
  Client/smug-tickets/vite.config.js
Labels: Revision

#101 Feature shop
  Client/smug-tickets/src/components/Button/LocationButton.jsx
  Client/smug-tickets/src/pages/user/Pay.jsx
  Client/smug-tickets/src/pages/user/PaymentInfo.jsx
  Client/smug-tickets/src/pages/user/TicketInformation.jsx
  Client/smug-tickets/src/pages/user/TicketPurchase.jsx
  Client/smug-tickets/src/routes/AppRouter.jsx
  Client/smug-tickets/src/services/Ticket/TicketService.js
Labels: enhancement

#102 :sparkles:Agregando QR del ticket
  Client/smug-tickets/src/components/Card/CardMyTicket.jsx
  Client/smug-tickets/src/pages/user/TicketPurchase.jsx
  Client/smug-tickets/src/pages/user/TransferTicket.jsx
  Client/smug-tickets/src/pages/user/ViewQR.jsx
  Client/smug-tickets/src/routes/AppRouter.jsx
Labels: Revision

#104 Feature api
  Client/smug-tickets/src/pages/admin/CreatEvent.jsx
  Client/smug-tickets/src/pages/admin/EditEvent.jsx
  Client/smug-tickets/src/pages/admin/NewLocation.jsx
  Client/smug-tickets/src/pages/admin/ViewEvent.jsx
  Client/smug-tickets/src/pages/user/Prueba.jsx
  Client/smug-tickets/src/pages/user/Prueba2.jsx
  Client/smug-tickets/src/pages/user/Prueba3.jsx
  Client/smug-tickets/src/pages/user/Prueba4.jsx
  Client/smug-tickets/src/pages/user/ViewEvent.jsx
  Client/smug-tickets/src/pages/user/ViewQR.jsx
  Client/smug-tickets/src/routes/AppRouter.jsx
  Client/smug-tickets/src/services/Event/EventService.js
  Server/api/src/main/java/com/example/demo/controllers/CategoriaController.java
  Server/api/src/main/java/com/example/demo/controllers/EmailController.java
  Server/api/src/main/java/com/example/demo/controllers/EventoController.java
  Server/api/src/main/java/com/example/demo/controllers/LugaresController.java
  Server/api/src/main/java/com/example/demo/controllers/RolController.java
  Server/api/src/main/java/com/example/demo/controllers/TicketController.java
  Server/api/src/main/java/com/example/demo/controllers/TraspasoTicketsController.java
  Server/api/src/main/java/com/example/demo/controllers/UserController.java
  Server/api/src/main/java/com/example/demo/controllers/UserRolController.java
  Server/api/src/main/java/com/example/demo/controllers/UsuariosAsignadosEventosController.java
  Server/api/src/main/java/com/example/demo/model/dto/CreareventoDTO.java
  Server/api/src/main/java/com/example/demo/model/entities/Evento.java
  Server/api/src/main/java/com/example/demo/services/implementation/LugaresImpl.java
Labels: Revision

#105 Feature tickets
  Client/smug-tickets/src/pages/user/TicketPurchase.jsx
  Server/api/src/main/java/com/example/demo/controllers/TicketController.java
  Server/api/src/main/java/com/example/demo/model/entities/Lugares.java
  Server/api/src/main/java/com/example/demo/repository/TicketRepository.java
  Server/api/src/main/java/com/example/demo/services/TicketsService.java
  Server/api/src/main/java/com/example/demo/services/implementation/TicketImpl.java
Labels: Revision

#107 :bug:Se arreglo en error al contabilizar los ticket vendidos
  Client/smug-tickets/src/pages/admin/GraphEvent.jsx
  Client/smug-tickets/src/pages/user/MyTIckets.jsx
  Client/smug-tickets/src/pages/user/Record.jsx
  Client/smug-tickets/src/services/Ticket/TicketService.js
  Client/smug-tickets/src/utils/pdfUtils.js
Labels: Revision
